In [14]:
import numpy as np

def matrix_mult(m1, m2):
    result = np.dot(m1.T, m2)
    return result

# Generate random values for matrix_1
matrix_1 = np.random.randint(1, 3, size=(3, 1))
print("Matrix 1:")
print(matrix_1)

# Generate random values for matrix_2
matrix_2 = np.random.randint(1, 10, size=(3, 3))
print("Matrix 2:")
print(matrix_2)

# Perform matrix multiplication
mult_result = matrix_mult(matrix_1, matrix_2)
print("Result of matrix multiplication:")
print(mult_result)


Matrix 1:
[[1]
 [2]
 [1]]
Matrix 2:
[[2 4 9]
 [8 3 3]
 [6 9 6]]
Result of matrix multiplication:
[[24 19 21]]
