In [ ]:
import numpy as np
a= np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
zeros_arr = np.zeros((3, 4))
print(zeros_arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
ones_arr = np.ones((2, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
range_arr = np.arange(0, 10, 2)
print(range_arr)

[0 2 4 6 8]


In [ ]:
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
import numpy as np
arr=np.arange(0,100,50)
reshaped_arr = np.reshape(arr, (2, 1))
print(reshaped_arr)

[[ 0]
 [50]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (6, 1))
print(reshaped_arr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
import numpy as np
md_arr=np.arange(1,15,1)
print(md_arr)
new_arr=np.reshape(md_arr,(7,2))
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]


In [ ]:
arr = np.array([[1, 2, 3,3],
                [4, 5, 6,4],
                [7, 8, 4,7]])
print(arr)
print(arr[0,1]) #print ist elemet of 2nd column
print(arr[0][1])#same as above
print(arr.shape)#Print dimentions of array
print(arr.size)#print total elements of arrays
rows=len(arr)
cols=len(arr[1])
print(rows ,cols)

[[1 2 3 3]
 [4 5 6 4]
 [7 8 4 7]]
2
2
(3, 4)
12
3 4


In [ ]:
import numpy as np
arr_ =np.arange(1,12,2)
print(arr_)

reshaped_arr = np.reshape(arr_, (2, 3))
print("Reshaped 2-D array:")
print(reshaped_arr)
b=np.ones((3,5))
print(b)


[ 1  3  5  7  9 11]
Reshaped 2-D array:
[[ 1  3  5]
 [ 7  9 11]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

constant_arr = np.full((2, 3), ['a', 'b', 'c'])
print(constant_arr)


[['a' 'b' 'c']
 ['a' 'b' 'c']]


In [ ]:
import numpy as np

constant_arr = np.full((2, 2), ['a'])
print(constant_arr)


[['a' 'a']
 ['a' 'a']]


In [ ]:
import numpy as np

constant_arr = np.arange(1,25,2)
print(constant_arr)
x=np.reshape(constant_arr,[3,4])
print(x)

arr_index= (x>2)
print(arr_index)


[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
[[False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [ ]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the dot product
dot_product = np.dot(vector1, vector2)
print("Dot Product:", dot_product)

dot_sum = np.sum(vector1)
print("Sum:", dot_sum)




Dot Product: 32
Dot Product: 6


In [ ]:
import numpy as np

# Create a 2-dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum the elements along axis 0 (column-wise sum)
sum_axis0 = np.sum(arr, axis=0)
print("Sum along axis 0:")
print(sum_axis0)
# sum_axis0 = [1+4, 2+5, 3+6] = [5, 7, 9]

# Sum the elements along axis 1 (row-wise sum)
sum_axis1 = np.sum(arr, axis=1)
print("Sum along axis 1:")
print(sum_axis1)
# sum_axis0 = [1+2+3, 4+5+6] = [6, 15]

# Sum all elements in the array
sum_all = np.sum(arr)
print("Sum of all elements:")
print(sum_all)


Sum along axis 0:
[5 7 9]
Sum along axis 1:
[ 6 15]
Sum of all elements:
21


In [ ]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Add the vectors element-wise
sum_vector = np.add(vector1, vector2)
print("Sum of vectors:", sum_vector)

sum_all = np.sum(vector1)
print("Sum of all elements:")
print(sum_all)


Sum of vectors: [5 7 9]
Sum of all elements:
6


In [ ]:
import pandas as pd